a=int (input("enter your name"))
b=int (input("enter your name"))
c=int (input("enter your name"))
print("addition :",a+b)
print("subraction :",a-b)
print("multiplication :",a*b)
print("division :",a/b)
print("floor division :",a//b)
print("modulas :",a%b)
print("power :",a**b)
print("cupe :",a**3)
print("Average :",a+b+c/3)
print(a>=b and a==b)
print(id(a))
integer=30
float=20
print(integer+float)
print(a>=b)
print(a==b)
print(a+b+c/3)
